--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/xJustJqy/Rankup-MineWarps
build-by-default: true
branches:
- main
projects:
  Rankup-MineWarps:
    path: ""
    icon: "rankup-minewarp.png"
...
